### ISSUE TITLE
abigen

### ISSUE THREAD

**Issue by quazzuk** [0xKitsune/cfmms-rs#66]
Hey Guys

Great work on `cfmm-rs` and `uniswapv3_math-rs`!!

Just had a question... I noticed in `uniswap_v3.rs` you are defining the swap event signature and writing code to decode swap logs, can't you instead just generate this code using abigen with `ethers-rs`?

Something like:

```
let event = UniswapV3PoolEvents::decode_log(&RawLog {
    topics: log.topics,
    data: log.data.to_vec(),
});
```

Thanks
Q

**Comment by 0xKitsune** [comment]
Yes I believe this (or something similar) would work. I don't think there is a runtime cost to getting the event signatures from abigen but that would be the only reason to use a const the way we do now.

As for decoding the log, this was just an early implementation that just hasnt been updated yet, feel free to open up an issue/PR if you would like!
