### ISSUE TITLE
Why use u128 instead of U256 for pool reserves?

### ISSUE THREAD

**Issue by 0xfourzerofour** [0xKitsune/cfmms-rs#95]
Not really an issue but just wondering why the pool definitions use u128 ints for the reserves as reserves on chain are u256?

**Comment by 0xOsiris** [comment]
> Not really an issue but just wondering why the pool definitions use u128 ints for the reserves as reserves on chain are u256?

Reserves are represented as u112's on v2 forks. No need to use a u256 since the reserve will never exceed the capacity of a u128.

**Comment by 0xfourzerofour** [comment]
@0xOsiris thanks for clarifying, Ive just been using U256 for the past while so that'll save some memory ahah
